### ISSUE TITLE
`docker.*` image options lost after `dapp dimg tag`

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#1029]
dappfile:

```yaml
dimg: ~
from: jenkins/jenkins:lts
docker:
  WORKDIR: /opt
  USER: jenkins
  EXPOSE: "8080"
```

Check last stage default user (OK):

```
$ docker run -ti dimgstage-ololo:020f1b11dcb9fdc753806c085abaa8f45a5d473469e50ddf414e65983811f309 id
uid=1000(jenkins) gid=1000(jenkins) groups=1000(jenkins)
```

Make dapp tag:

```
$ dapp dimg tag myimage --tag mytag
```

Check default user by tag (FAIL):

```
$ docker run -ti myimage:mytag id
uid=0(root) gid=0(root) groups=0(root)
```
