### ISSUE TITLE
Problem with rsync (permission denied) after upgrade to 0.36.10

### ISSUE THREAD

**Issue by kovetskiy** [flant/dapp#1136]
Hello, I've updated dapp from 0.23 to 0.36.10, but now I've got problem with build:

```
      Setup                                                                                          [OK] 184.53 sec
        signature: dimgstage-frontend:9c366216d909c9f7436075994ecefe132d2c5625ef81fd9f60dd9456b16b43e3
        commands:
          cd /app
          npm run build
          mkdir /app/dist/api
          chmod 755 /app/dist/deploy.sh
          chmod 755 /app/dist/post-deploy.sh
          echo 'b31080e8dc7e53331735cecf5c095831c8b188a8' > /dist/api/status
  building artifact `frontend`                                                            [OK] 415.56 sec
  copying artifact `frontend` ...
rsync: mkdir "/.dapp/tmp/frontend/7c3b0ab9-5a67-45c1-bba6-5e41515ed3e5" failed: Permission denied (13)
rsync error: error in file IO (code 11) at main.c(657) [Receiver=3.1.2]
                                                    [FAILED] 1.31 sec
Stacktrace dumped to /tmp/dapp-stacktrace-8cf5bf15-0018-465f-8cd2-8f1f3ceef8f4.out
ruby2go_image command `container_run` failed: `Status: , Code: 11`!
Running time 500.34 seconds
ERROR: Job failed: exit status 1
```

my dappfile:
```
artifact: {{ env "CI_PROJECT_PATH_SLUG" }}
from: {{ env "BUILD_NODE_IMAGE" }}

mount:
  - from: build_dir
    to: /app/.npm

shell:
  install:
    - cd /app
    - npm install

  setup:
    - cd /app
    - npm run build
    - mkdir /app/dist/api
    - chmod 755 /app/dist/deploy.sh
    - chmod 755 /app/dist/post-deploy.sh
    - echo '{{ env "CI_COMMIT_SHA" }}' > /app/dist/api/status

git:
  - add: /
    to: /app
    owner: app
    group: app

    stageDependencies:
      install:
        - package.json
        - package-lock.json
      setup:
        - "src/*"
        - "bin/*"
        - "assets/*"

---
dimg: {{ env "CI_PROJECT_PATH" }}/{{ env "CI_COMMIT_REF_SLUG" }}
from: {{ env "PROD_NGINX_IMAGE" }}

docker:
  EXPOSE: '80'

import:
  - artifact: {{ env "CI_PROJECT_PATH_SLUG" }}
    add: /app/dist
    to: /app
    after: setup
    owner: app
    group: app

```

The same build works for 0.23 after downgrade. 

build command:
```
dapp dimg build --verbose --name $CI_PROJECT_PATH_SLUG
```
