### ISSUE TITLE
"Глобальные" переменные среды, доступные на всех этапах сборки, а также при запуске образа

### ISSUE THREAD

**Issue by diafour** [flant/dapp#188]
Как разработчик Dappfile, хочу определить некоторые переменные среды, которые были бы доступны на любой стадии (и для shell и для chef), а также при запуске образа. Сейчас docker.env выполняется в последний момент - эти переменные среды доступны только после запуска образа. 

Сейчас в одном приложении получается следующее: 
* переменные устанавливаем один раз в атрибутах dimod, чтобы скачались правильные зависимости
* второй раз в рецепте приложения, чтобы сделать конфиг
* и третий раз в docker.env, т.к. переменные нужны для запуска приложения

Хотелось бы иметь механизм установки "глобальных" переменных, чтобы не повторять их по нескольку раз.

**Comment by alexey-igrychev** [comment]
как workaround можно использовать следующее решение:
```
dimg: from
from: alpine
git:
- add: /
  to: /app
---
dimg: app
fromDimg: from
shell:
  setup: command
```
