### ISSUE TITLE
Git stageDependencies unclear behaviour with single-file git-add

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#664]
```
git:
- add: /myfile
  to: /myapp/myfile
  stageDependencies:
    setup:
    - myfile
```

WIll not work as expected: set setup-stage rebuild trigger on `/myfile` changes.

Though, the following configuration will work:

```
git:
- add: /myfile
  to: /myapp/myfile
  stageDependencies:
    setup:
    - ""
```

**Comment by alexey-igrychev** [comment]
```
git:
- add: /
  to: /myapp/myfile
  includePaths:
  - myfile
  stageDependencies:
    setup:
    - myfile
```
