### ISSUE TITLE
Add info about CacheVersion yaml directives for ansible and shell

### ISSUE THREAD

**Issue by distorhead** [flant/dapp#839]
beforeInstallCacheVersion, installCacheVersion, beforeSetupCacheVersion, setupCacheVersion

for ansible and shell builders

```
ansible:
  beforeInstallCacheVersion: 1
  beforeInstall:
    - name: hello
      apt:
        name: nginx-extras  
```
