### ISSUE TITLE
AWS IAM Authentication is not supported

### ISSUE THREAD

**Issue by maxd** [flant/dapp#906]
Hello,

[Here](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html) is described how to configure kubeconfig to connect to AWS EKS.

As you can see this config is using custom authenticator specified in `exec` section:

```
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "<cluster-name>"
        # - "-r"
        # - "<role-arn>"
      # env:
        # - name: AWS_PROFILE
        #   value: "<aws-profile>"
```

but `dapp` doesn't support custom authenticators (details [here](https://github.com/flant/dapp/blob/master/lib/dapp/kube/kubernetes/client.rb#L278-L309)).

So, right now `dapp` can't establish connection to AWS EKS cluster.

My questions:

1) Will you implement support of custom authenticators? Any estimates?
2) Can you provide workaround to solve this problem?

Thank you.
